"""empty message

Revision ID: 6b982b118612
Revises: 7cdd3af0013b
Create Date: 2020-05-31 03:12:09.337536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b982b118612'
down_revision = '7cdd3af0013b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('nus_net_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_nus_net_id'), 'users', ['nus_net_id'], unique=True)
    op.create_table('user_mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('mod_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('class_grp', sa.String(length=6), nullable=True),
    sa.Column('term', sa.String(length=6), nullable=True),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mods_class_grp'), 'user_mods', ['class_grp'], unique=False)
    op.create_index(op.f('ix_user_mods_code'), 'user_mods', ['code'], unique=False)
    op.create_index(op.f('ix_user_mods_id'), 'user_mods', ['id'], unique=False)
    op.create_index(op.f('ix_user_mods_mod_id'), 'user_mods', ['mod_id'], unique=False)
    op.create_index(op.f('ix_user_mods_term'), 'user_mods', ['term'], unique=False)
    op.drop_index('ix_user__mods_class_grp', table_name='user__mods')
    op.drop_index('ix_user__mods_code', table_name='user__mods')
    op.drop_index('ix_user__mods_id', table_name='user__mods')
    op.drop_index('ix_user__mods_mod_id', table_name='user__mods')
    op.drop_index('ix_user__mods_term', table_name='user__mods')
    op.drop_table('user__mods')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_nus_net_id', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('nus_net_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_nus_net_id', 'user', ['nus_net_id'], unique=1)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_table('user__mods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=8), nullable=True),
    sa.Column('mod_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('class_grp', sa.VARCHAR(length=6), nullable=True),
    sa.Column('term', sa.VARCHAR(length=6), nullable=True),
    sa.Column('student', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user__mods_term', 'user__mods', ['term'], unique=False)
    op.create_index('ix_user__mods_mod_id', 'user__mods', ['mod_id'], unique=False)
    op.create_index('ix_user__mods_id', 'user__mods', ['id'], unique=False)
    op.create_index('ix_user__mods_code', 'user__mods', ['code'], unique=False)
    op.create_index('ix_user__mods_class_grp', 'user__mods', ['class_grp'], unique=False)
    op.drop_index(op.f('ix_user_mods_term'), table_name='user_mods')
    op.drop_index(op.f('ix_user_mods_mod_id'), table_name='user_mods')
    op.drop_index(op.f('ix_user_mods_id'), table_name='user_mods')
    op.drop_index(op.f('ix_user_mods_code'), table_name='user_mods')
    op.drop_index(op.f('ix_user_mods_class_grp'), table_name='user_mods')
    op.drop_table('user_mods')
    op.drop_index(op.f('ix_users_nus_net_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
