"""empty message

Revision ID: d47a47297961
Revises: 7d83be0f1ef8
Create Date: 2020-05-29 22:01:45.813039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47a47297961'
down_revision = '7d83be0f1ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user__mods_student'), 'user__mods', ['student'], unique=False)
    op.drop_constraint(None, 'user__mods', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user__mods', 'user', ['student'], ['nus_net_id'])
    op.drop_index(op.f('ix_user__mods_student'), table_name='user__mods')
    # ### end Alembic commands ###
